[package]
name = "data_plus"
version = "0.1.0"
authors = ["yang"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
easy-db-derive = { path = "easy-db-derive" }
chrono = "0.4"
mysql = "*"